# Static config - Only load when start Traefik
global:
  checkNewVersion: false
  sendAnonymousUsage: false

# Entrypoints - define ports Traefik will listen on
entryPoints:
  web:
    address: ":80"
    # No HTTPS redirect - Cloudflare handles SSL

# Providers - define how Traefik discovers services
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false # Only expose services with traefik.enable=true
    network: jarvis-proxy
  
  file:
    directory: /etc/traefik/
    watch: true

# No SSL certificates needed - Cloudflare handles SSL

# API and Dashboard
api:
  dashboard: true
  insecure: true # Enable insecure mode for debugging
  # Disable debug API dashboard, only use routed dashboard
  debug: false

# Logging
log:
  level: DEBUG
  filePath: /var/log/traefik/traefik.log

accessLog:
  filePath: /var/log/traefik/access.log

# Metrics - Prometheus
metrics:
  prometheus:
    addRoutersLabels: true
    addServicesLabels: true