# Shared Middlewares for all services
http:
  middlewares:
    # Security headers
    securityHeaders:
      headers:
        accessControlAllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        accessControlMaxAge: 100
        hostsProxyHeaders:
          - X-Forwarded-Host
        referrerPolicy: "same-origin"
        customRequestHeaders:
          X-Forwarded-Proto: "https"

    # Rate limiting
    rateLimit:
      rateLimit:
        average: 100
        burst: 20

    # Compression
    compress: {}

    # Origin restriction for homecam API - only allow requests from frontend
    homecamOriginCheck:
      headers:
        customRequestHeaders:
          X-Required-Origin: "https://homecam.thanhpt.xyz"
        customResponseHeaders:
          X-Restricted-API: "homecam-frontend-only"

    # CORS for frontend apps (restrictive) - DISABLED FOR DEBUG
    # corsApi:
    #   headers:
    #     accessControlAllowOriginList:
    #       - "https://*.thanhpt.xyz"
    #     accessControlAllowMethods:
    #       - GET
    #       - POST
    #       - PUT
    #       - DELETE
    #       - OPTIONS
    #     accessControlAllowHeaders:
    #       - "Content-Type"
    #       - "Authorization"
    #     accessControlAllowCredentials: true

    # CORS for homecam API (restrictive to specific frontend)
    corsHomecam:
      headers:
        customResponseHeaders:
          Access-Control-Allow-Origin: "https://homecam.thanhpt.xyz"
          Access-Control-Allow-Methods: "GET,POST,PUT,DELETE,OPTIONS"
          Access-Control-Allow-Headers: "Content-Type,Authorization"
          Access-Control-Allow-Credentials: "true"

    # CORS for public APIs
    corsPublic:
      headers:
        accessControlAllowOriginList:
          - "*"
        accessControlAllowMethods:
          - GET
          - OPTIONS 